### ISSUE TITLE
scala version of Haskell Quicksort solution

### ISSUE THREAD

**Issue by philipschwarz** [ashwinbhaskar/functional-way#20]
Hello there,

this is not really an issue. FWIW I just wanted to show the Scala equivalent of https://github.com/ashwinbhaskar/functional-way/blob/master/haskell-way/src/QuickSort.hs.

I came across it here: https://www.slideshare.net/pjschwarz/ad-hoc-polymorphism-using-type-classes-and-cats#2

Cheers.

**Comment by ashwinbhaskar** [comment]
@philipschwarz hey, this is nice! I will take a look at it. Meanwhile, I have changed the implementation of Quicksort in Scala to do the swapping in an immutable way

**Comment by ashwinbhaskar** [comment]
@philipschwarz But I agree that the current implementation in scala feels more imperative. It's no where near the haskell implementation

**Comment by ashwinbhaskar** [comment]
@philipschwarz done. Have implemented something similar but using Arrays:) Thank you for raising the issue.

**Comment by philipschwarz** [comment]
cool - thanks for following up - 👍
