### ISSUE TITLE
Confusing comment for transformBST

### ISSUE THREAD

**Issue by jvanbruegge** [ashwinbhaskar/functional-way#7]
In the scala transformBST code, you have this comment: https://github.com/ashwinbhaskar/functional-way/blob/master/scala-way/src/main/scala/tree/TransformBST.scala#L3
But the tree underneath is doing something completely different.
First it is not summing nodes greater or equal, it is excluding itself. But then the two 6es should still have the same value. So what I think this does is just summing the values that are to the left, am I right?

**Comment by ashwinbhaskar** [comment]
@jvanbruegge Yes, the comment is faulty. I will rectify it right away and push. It should update the node value with the sum of node values that are greater than the node's present value.

**Comment by ashwinbhaskar** [comment]
@jvanbruegge pushed the corrected problem statement
